# all case insensitive

<A> ::= "a" | "an"
<opt x> ::= ("" | x)

<neu-type> ::= <datum> | <neu-generic-type> | <neu-function-type>
<neu-generic-type> ::= <symbol> <datum>
<neu-function-type> ::= <opt <neu-type-args>> <datum>+ "->" <datum>
   <neu-type-args> ::= "{" <symbol>* "}"

<neu-comment> ::= ";" (<neu-template> | <neu-annotation> | <neu-alias>)
   <neu-annotation> ::= <symbol> ":" <datum>
   <neu-template> ::= "template" <opt ":"> <lf> ";" <neu-annotation>
   <neu-alias> ::= <A> <symbol> "is" (<neu-simple-alias> | <neu-union>)
      <neu-simple-alias> ::= <opt <A>> <datum> <lf>
      <neu-union> ::= "one of" <lf> <neu-union-member>+
         <neu-union-member> ::= "; - " <neu-type> <lf>
